/**
 * TRIBAL LLM - Model Registry
 *
 * Registre des modeles disponibles via OpenRouter.
 * Architecture extensible : chaque provider peut avoir son propre catalogue.
 */

export interface LlmModelInfo {
  id: string // e.g. "openai/gpt-4o"
  name: string // e.g. "GPT-4o"
  provider: string // e.g. "OpenAI"
  providerSlug: string // e.g. "openrouter"
  description: string
  contextWindow: number // tokens
  maxOutput?: number
  inputPrice: number // $ per 1M tokens
  outputPrice: number // $ per 1M tokens
  category: LlmModelCategory
  capabilities: LlmCapability[]
  isDefault?: boolean
  isFeatured?: boolean
  iconColor?: string
}

export type LlmModelCategory =
  | 'flagship'
  | 'fast'
  | 'reasoning'
  | 'coding'
  | 'creative'
  | 'vision'
  | 'free'
  | 'open-source'

export type LlmCapability =
  | 'chat'
  | 'code'
  | 'vision'
  | 'function-calling'
  | 'json-mode'
  | 'reasoning'
  | 'long-context'

export const MODEL_CATEGORIES: Record<LlmModelCategory, { label: string; color: string }> = {
  flagship: { label: 'Premium', color: 'from-amber-500 to-orange-500' },
  fast: { label: 'Rapide', color: 'from-green-500 to-emerald-500' },
  reasoning: { label: 'Raisonnement', color: 'from-purple-500 to-violet-500' },
  coding: { label: 'Code', color: 'from-blue-500 to-cyan-500' },
  creative: { label: 'Creatif', color: 'from-pink-500 to-rose-500' },
  vision: { label: 'Vision', color: 'from-indigo-500 to-blue-500' },
  free: { label: 'Gratuit', color: 'from-gray-500 to-slate-500' },
  'open-source': { label: 'Open Source', color: 'from-teal-500 to-green-500' },
}

/**
 * Catalogue principal des modeles OpenRouter
 * Prix en $ par million de tokens (input/output)
 * Mis a jour : Fevrier 2026
 */
export const OPENROUTER_MODELS: LlmModelInfo[] = [
  // ─── Flagship (Premium) ───────────────────────────────────────────────

  {
    id: 'anthropic/claude-opus-4.6',
    name: 'Claude Opus 4.6',
    provider: 'Anthropic',
    providerSlug: 'openrouter',
    description: 'Le plus puissant Anthropic - contexte 1M, raisonnement profond',
    contextWindow: 1000000,
    maxOutput: 32000,
    inputPrice: 5,
    outputPrice: 25,
    category: 'flagship',
    capabilities: [
      'chat',
      'code',
      'vision',
      'function-calling',
      'json-mode',
      'reasoning',
      'long-context',
    ],
    isFeatured: true,
    iconColor: '#D97757',
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    providerSlug: 'openrouter',
    description: 'Dernier Sonnet - excellent equilibre performance/prix, contexte 1M',
    contextWindow: 1000000,
    maxOutput: 16384,
    inputPrice: 3,
    outputPrice: 15,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    isDefault: true,
    isFeatured: true,
    iconColor: '#D97757',
  },
  {
    id: 'openai/gpt-5.2',
    name: 'GPT-5.2',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Dernier modele phare OpenAI - contexte 400K',
    contextWindow: 400000,
    maxOutput: 32000,
    inputPrice: 1.75,
    outputPrice: 14,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    isFeatured: true,
    iconColor: '#10A37F',
  },
  {
    id: 'google/gemini-3-pro-preview',
    name: 'Gemini 3 Pro',
    provider: 'Google',
    providerSlug: 'openrouter',
    description: 'Nouveau Gemini 3 Pro - contexte 1M, multimodal avance',
    contextWindow: 1048576,
    maxOutput: 32000,
    inputPrice: 2,
    outputPrice: 12,
    category: 'flagship',
    capabilities: [
      'chat',
      'code',
      'vision',
      'function-calling',
      'json-mode',
      'reasoning',
      'long-context',
    ],
    isFeatured: true,
    iconColor: '#4285F4',
  },
  {
    id: 'google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    providerSlug: 'openrouter',
    description: 'Modele avance Google avec fenetre de contexte massive et raisonnement',
    contextWindow: 1048576,
    maxOutput: 65536,
    inputPrice: 1.25,
    outputPrice: 10,
    category: 'flagship',
    capabilities: [
      'chat',
      'code',
      'vision',
      'function-calling',
      'json-mode',
      'reasoning',
      'long-context',
    ],
    iconColor: '#4285F4',
  },
  {
    id: 'anthropic/claude-opus-4.5',
    name: 'Claude Opus 4.5',
    provider: 'Anthropic',
    providerSlug: 'openrouter',
    description: 'Opus 4.5 - ideal pour les taches complexes, contexte 200K',
    contextWindow: 200000,
    maxOutput: 16384,
    inputPrice: 5,
    outputPrice: 25,
    category: 'flagship',
    capabilities: [
      'chat',
      'code',
      'vision',
      'function-calling',
      'json-mode',
      'reasoning',
      'long-context',
    ],
    iconColor: '#D97757',
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'Anthropic',
    providerSlug: 'openrouter',
    description: 'Sonnet 4 - excellent rapport qualite/prix, contexte 1M',
    contextWindow: 1000000,
    maxOutput: 16384,
    inputPrice: 3,
    outputPrice: 15,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#D97757',
  },
  {
    id: 'openai/gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'GPT-5 - contexte 400K, multimodal avance',
    contextWindow: 400000,
    maxOutput: 32000,
    inputPrice: 1.25,
    outputPrice: 10,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#10A37F',
  },

  // ─── Fast (Rapide) ────────────────────────────────────────────────────

  {
    id: 'anthropic/claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    providerSlug: 'openrouter',
    description: 'Rapide et economique - ideal pour les taches courantes',
    contextWindow: 200000,
    maxOutput: 8192,
    inputPrice: 1,
    outputPrice: 5,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#D97757',
  },
  {
    id: 'openai/gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'GPT-5 leger et rapide, contexte 400K',
    contextWindow: 400000,
    maxOutput: 16384,
    inputPrice: 0.25,
    outputPrice: 2,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#10A37F',
  },
  {
    id: 'google/gemini-3-flash-preview',
    name: 'Gemini 3 Flash',
    provider: 'Google',
    providerSlug: 'openrouter',
    description: 'Gemini 3 Flash - rapide et economique, contexte 1M',
    contextWindow: 1048576,
    maxOutput: 16384,
    inputPrice: 0.5,
    outputPrice: 3,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#4285F4',
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    providerSlug: 'openrouter',
    description: 'Flash rapide avec raisonnement, contexte 1M',
    contextWindow: 1048576,
    maxOutput: 16384,
    inputPrice: 0.3,
    outputPrice: 2.5,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#4285F4',
  },
  {
    id: 'openai/gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Ultra-leger OpenAI, tres economique',
    contextWindow: 400000,
    maxOutput: 8192,
    inputPrice: 0.05,
    outputPrice: 0.4,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#10A37F',
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Version legere de GPT-4o, tres rapide',
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 0.15,
    outputPrice: 0.6,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode'],
    iconColor: '#10A37F',
  },

  // ─── Reasoning (Raisonnement) ─────────────────────────────────────────

  {
    id: 'openai/o4-mini',
    name: 'o4 Mini',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Dernier modele de raisonnement OpenAI',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#10A37F',
  },
  {
    id: 'openai/o3',
    name: 'o3',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Raisonnement avance OpenAI o3',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 2,
    outputPrice: 8,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#10A37F',
  },
  {
    id: 'deepseek/deepseek-r1-0528',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerSlug: 'openrouter',
    description: 'Raisonnement open-source, contexte 164K',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0.4,
    outputPrice: 1.75,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#4D6BFE',
  },

  // ─── Coding ───────────────────────────────────────────────────────────

  {
    id: 'openai/gpt-5.1-codex',
    name: 'GPT-5.1 Codex',
    provider: 'OpenAI',
    providerSlug: 'openrouter',
    description: 'Specialise code OpenAI, contexte 400K',
    contextWindow: 400000,
    maxOutput: 32000,
    inputPrice: 1.25,
    outputPrice: 10,
    category: 'coding',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#10A37F',
  },
  {
    id: 'mistralai/codestral-2508',
    name: 'Codestral',
    provider: 'Mistral',
    providerSlug: 'openrouter',
    description: 'Specialise code par Mistral, contexte 256K',
    contextWindow: 256000,
    maxOutput: 16384,
    inputPrice: 0.3,
    outputPrice: 0.9,
    category: 'coding',
    capabilities: ['chat', 'code', 'long-context'],
    iconColor: '#FF7000',
  },
  {
    id: 'mistralai/devstral-medium',
    name: 'Devstral Medium',
    provider: 'Mistral',
    providerSlug: 'openrouter',
    description: 'Dev-focused de Mistral, contexte 131K',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0.4,
    outputPrice: 2,
    category: 'coding',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#FF7000',
  },
  {
    id: 'deepseek/deepseek-v3.2',
    name: 'DeepSeek V3.2',
    provider: 'DeepSeek',
    providerSlug: 'openrouter',
    description: 'Dernier DeepSeek - excellent pour le code, tres economique',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0.25,
    outputPrice: 0.38,
    category: 'coding',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode'],
    iconColor: '#4D6BFE',
  },

  // ─── Open Source ──────────────────────────────────────────────────────

  {
    id: 'meta-llama/llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    providerSlug: 'openrouter',
    description: 'Llama 4 - nouvelle generation Meta, contexte 1M',
    contextWindow: 1048576,
    maxOutput: 16384,
    inputPrice: 0.15,
    outputPrice: 0.6,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling', 'long-context'],
    iconColor: '#0668E1',
  },
  {
    id: 'meta-llama/llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    providerSlug: 'openrouter',
    description: 'Llama 4 Scout - leger et rapide, contexte 328K',
    contextWindow: 327680,
    maxOutput: 16384,
    inputPrice: 0.08,
    outputPrice: 0.3,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#0668E1',
  },
  {
    id: 'mistralai/mistral-medium-3.1',
    name: 'Mistral Medium 3.1',
    provider: 'Mistral',
    providerSlug: 'openrouter',
    description: 'Mistral Medium derniere version, multilingue',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0.4,
    outputPrice: 2,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#FF7000',
  },

  // ─── Free (Gratuit) ──────────────────────────────────────────────────

  {
    id: 'deepseek/deepseek-r1-0528:free',
    name: 'DeepSeek R1 (Gratuit)',
    provider: 'DeepSeek',
    providerSlug: 'openrouter',
    description: 'Raisonnement DeepSeek R1 gratuit sur OpenRouter',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'free',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#4D6BFE',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Llama 3.3 70B (Gratuit)',
    provider: 'Meta',
    providerSlug: 'openrouter',
    description: 'Meta Llama 3.3 70B gratuit, contexte 128K',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'free',
    capabilities: ['chat', 'code', 'function-calling', 'long-context'],
    iconColor: '#0668E1',
  },
  {
    id: 'mistralai/mistral-small-3.1-24b-instruct:free',
    name: 'Mistral Small 3.1 (Gratuit)',
    provider: 'Mistral',
    providerSlug: 'openrouter',
    description: 'Mistral Small gratuit, bon pour les taches courantes',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'free',
    capabilities: ['chat', 'code'],
    iconColor: '#FF7000',
  },
]

/**
 * Catalogue des modeles GitHub Models
 * Inclus gratuitement avec GitHub Copilot Pro
 * Mis a jour : Fevrier 2026
 */
export const GITHUB_MODELS: LlmModelInfo[] = [
  // ─── OpenAI Flagship ──────────────────────────────────────────────────
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-4o via GitHub - gratuit avec Copilot Pro',
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-4.1',
    name: 'GPT-4.1',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-4.1 via GitHub - gratuit avec Copilot Pro',
    contextWindow: 1048576,
    maxOutput: 32768,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-5 via GitHub - gratuit avec Copilot Pro',
    contextWindow: 400000,
    maxOutput: 32000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-5-chat',
    name: 'GPT-5 Chat',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-5 Chat preview via GitHub - conversations avancees',
    contextWindow: 400000,
    maxOutput: 32000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },

  // ─── OpenAI Fast ──────────────────────────────────────────────────────
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-4o Mini via GitHub - rapide et gratuit',
    contextWindow: 128000,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-4.1 Mini via GitHub - rapide et gratuit',
    contextWindow: 1048576,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-4.1 Nano via GitHub - ultra rapide et gratuit',
    contextWindow: 1048576,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-5 Mini via GitHub - rapide et gratuit',
    contextWindow: 400000,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'vision', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'GPT-5 Nano via GitHub - ultra rapide et gratuit',
    contextWindow: 400000,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling', 'json-mode', 'long-context'],
    iconColor: '#24292F',
  },

  // ─── OpenAI Reasoning ─────────────────────────────────────────────────
  {
    id: 'openai/o1',
    name: 'o1',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'o1 via GitHub - raisonnement avance gratuit',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/o3',
    name: 'o3',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'o3 via GitHub - raisonnement avance gratuit',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/o3-mini',
    name: 'o3 Mini',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'o3 Mini via GitHub - raisonnement rapide gratuit',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'openai/o4-mini',
    name: 'o4 Mini',
    provider: 'OpenAI',
    providerSlug: 'github',
    description: 'o4 Mini via GitHub - raisonnement rapide gratuit',
    contextWindow: 200000,
    maxOutput: 100000,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#24292F',
  },

  // ─── DeepSeek ─────────────────────────────────────────────────────────
  {
    id: 'deepseek/DeepSeek-R1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    providerSlug: 'github',
    description: 'DeepSeek R1 via GitHub - raisonnement gratuit',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#24292F',
  },
  {
    id: 'deepseek/DeepSeek-R1-0528',
    name: 'DeepSeek R1 0528',
    provider: 'DeepSeek',
    providerSlug: 'github',
    description: 'DeepSeek R1 0528 via GitHub - raisonnement ameliore',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#24292F',
  },
  {
    id: 'deepseek/DeepSeek-V3-0324',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    providerSlug: 'github',
    description: 'DeepSeek V3 via GitHub - modele polyvalent gratuit',
    contextWindow: 163840,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },

  // ─── Microsoft ────────────────────────────────────────────────────────
  {
    id: 'microsoft/MAI-DS-R1',
    name: 'MAI-DS-R1',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Microsoft MAI-DS-R1 via GitHub - raisonnement gratuit',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#24292F',
  },

  // ─── Meta Open Source ─────────────────────────────────────────────────
  {
    id: 'meta/Meta-Llama-3.1-8B-Instruct',
    name: 'Llama 3.1 8B',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 3.1 8B via GitHub - compact et gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Meta-Llama-3.1-405B-Instruct',
    name: 'Llama 3.1 405B',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 3.1 405B via GitHub - le plus grand Llama gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Llama-3.2-11B-Vision-Instruct',
    name: 'Llama 3.2 11B Vision',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 3.2 11B Vision via GitHub - vision gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'vision'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Llama-3.2-90B-Vision-Instruct',
    name: 'Llama 3.2 90B Vision',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 3.2 90B Vision via GitHub - vision puissant gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'vision'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Llama-3.3-70B-Instruct',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 3.3 70B via GitHub - open source gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Llama-4-Scout-17B-16E-Instruct',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 4 Scout via GitHub - open source gratuit',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'meta/Llama-4-Maverick-17B-128E-Instruct-FP8',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    providerSlug: 'github',
    description: 'Llama 4 Maverick via GitHub - open source gratuit',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },

  // ─── Microsoft Phi ────────────────────────────────────────────────────
  {
    id: 'microsoft/Phi-4',
    name: 'Phi 4',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Phi 4 via GitHub - compact et gratuit',
    contextWindow: 16384,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code'],
    iconColor: '#24292F',
  },
  {
    id: 'microsoft/Phi-4-mini-instruct',
    name: 'Phi 4 Mini',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Phi 4 Mini via GitHub - ultra compact gratuit',
    contextWindow: 16384,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'microsoft/Phi-4-mini-reasoning',
    name: 'Phi 4 Mini Reasoning',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Phi 4 Mini Reasoning via GitHub - raisonnement compact gratuit',
    contextWindow: 16384,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#24292F',
  },
  {
    id: 'microsoft/Phi-4-multimodal-instruct',
    name: 'Phi 4 Multimodal',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Phi 4 Multimodal via GitHub - text/audio/image gratuit',
    contextWindow: 16384,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'vision'],
    iconColor: '#24292F',
  },
  {
    id: 'microsoft/Phi-4-reasoning',
    name: 'Phi 4 Reasoning',
    provider: 'Microsoft',
    providerSlug: 'github',
    description: 'Phi 4 Reasoning via GitHub - raisonnement avance gratuit',
    contextWindow: 16384,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'reasoning',
    capabilities: ['chat', 'code', 'reasoning'],
    iconColor: '#24292F',
  },

  // ─── Mistral ──────────────────────────────────────────────────────────
  {
    id: 'Codestral-2501',
    name: 'Codestral',
    provider: 'Mistral',
    providerSlug: 'github',
    description: 'Codestral via GitHub - code specialise gratuit',
    contextWindow: 256000,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code'],
    iconColor: '#24292F',
  },
  {
    id: 'mistral-small-2503',
    name: 'Mistral Small 3.1',
    provider: 'Mistral',
    providerSlug: 'github',
    description: 'Mistral Small 3.1 via GitHub - rapide et gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'mistral-medium-2505',
    name: 'Mistral Medium 3',
    provider: 'Mistral',
    providerSlug: 'github',
    description: 'Mistral Medium 3 via GitHub - equilibre et gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'Ministral-3B',
    name: 'Ministral 3B',
    provider: 'Mistral',
    providerSlug: 'github',
    description: 'Ministral 3B via GitHub - ultra compact gratuit',
    contextWindow: 128000,
    maxOutput: 8192,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code'],
    iconColor: '#24292F',
  },

  // ─── Cohere ───────────────────────────────────────────────────────────
  {
    id: 'cohere/Cohere-command-r-08-2024',
    name: 'Command R',
    provider: 'Cohere',
    providerSlug: 'github',
    description: 'Command R via GitHub - RAG optimise gratuit',
    contextWindow: 128000,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'open-source',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'cohere/Cohere-command-r-plus-08-2024',
    name: 'Command R+',
    provider: 'Cohere',
    providerSlug: 'github',
    description: 'Command R+ via GitHub - RAG premium gratuit',
    contextWindow: 128000,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'cohere/cohere-command-a',
    name: 'Command A',
    provider: 'Cohere',
    providerSlug: 'github',
    description: 'Command A via GitHub - dernier modele Cohere gratuit',
    contextWindow: 128000,
    maxOutput: 4096,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },

  // ─── xAI ──────────────────────────────────────────────────────────────
  {
    id: 'xai/grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    providerSlug: 'github',
    description: 'Grok 3 via GitHub - gratuit avec Copilot Pro',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'flagship',
    capabilities: ['chat', 'code', 'function-calling'],
    iconColor: '#24292F',
  },
  {
    id: 'xai/grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xAI',
    providerSlug: 'github',
    description: 'Grok 3 Mini via GitHub - rapide et gratuit',
    contextWindow: 131072,
    maxOutput: 16384,
    inputPrice: 0,
    outputPrice: 0,
    category: 'fast',
    capabilities: ['chat', 'code', 'reasoning', 'function-calling'],
    iconColor: '#24292F',
  },
]

/**
 * Tous les modeles disponibles (OpenRouter + GitHub)
 */
export const ALL_MODELS: LlmModelInfo[] = [...OPENROUTER_MODELS, ...GITHUB_MODELS]

/**
 * Obtenir le modele par defaut
 */
export function getDefaultModel(): LlmModelInfo {
  return OPENROUTER_MODELS.find(m => m.isDefault) || OPENROUTER_MODELS[0]
}

/**
 * Trouver un modele par son ID
 */
export function findModelById(id: string): LlmModelInfo | undefined {
  return ALL_MODELS.find(m => m.id === id)
}

/**
 * Obtenir les modeles d'une categorie
 */
export function getModelsByCategory(category: LlmModelCategory): LlmModelInfo[] {
  return ALL_MODELS.filter(m => m.category === category)
}

/**
 * Obtenir les modeles mis en avant
 */
export function getFeaturedModels(): LlmModelInfo[] {
  return ALL_MODELS.filter(m => m.isFeatured)
}

/**
 * Formater le prix pour affichage
 */
export function formatPrice(pricePerMillion: number): string {
  if (pricePerMillion === 0) return 'Gratuit'
  if (pricePerMillion < 0.01) return `$${pricePerMillion.toFixed(4)}/1M`
  if (pricePerMillion < 1) return `$${pricePerMillion.toFixed(2)}/1M`
  return `$${pricePerMillion.toFixed(1)}/1M`
}

/**
 * Estimer le cout d'un message
 */
export function estimateCost(
  model: LlmModelInfo,
  inputTokens: number,
  outputTokens: number
): number {
  return (inputTokens * model.inputPrice + outputTokens * model.outputPrice) / 1_000_000
}
